if file_exists("FNASSave.r2save"){
    ini_open("FNASSave.r2save")
        global.Night = ini_read_real("Save", "Night", 1)
        global.N6 = ini_read_real("Unlocks", "Night 6", 0)
        global.Extras = ini_read_real("Unlocks", "Extras", 0)
        global.N5Star = ini_read_real("Stars", "Night 5", 0)
        global.N6Star = ini_read_real("Stars", "Night 6", 0)
        global.Four20Star = ini_read_real("Stars", "5/20", 0)
        global.N8Star = ini_read_real("Stars", "Night 8", 0)
        global.RingStar = ini_read_real("Stars", "Ring's Night", 0)
        global.SurvRecord = ini_read_real("Survival", "Record", 0)
        global.SurvMed = ini_read_real("Survival", "MediumRecord", 0)
        global.SurvHard = ini_read_real("Survival", "HardRecord", 0)
        global.GoldenPlush = ini_read_real("Plushies", "Golden", 0)
        global.SonicPlush = ini_read_real("Plushies", "Sonic", 0)
        global.MarioPlush = ini_read_real("Plushies", "Mario", 0)
        global.YoshiPlush = ini_read_real("Plushies", "Yoshi", 0)
        global.TailsPlush = ini_read_real("Plushies", "Tails", 0)
        global.RingPlush = ini_read_real("Plushies", "Ring", 0)
        global.JaxonPlush = ini_read_real("Plushies", "Jaxon", 0)
        global.ZertyPlush = ini_read_real("Plushies", "Zerty", 0)
        global.BlueFoxPlush = ini_read_real("Plushies", "BlueFox", 0)
        global.RingHat = ini_read_real("Plushies", "RingHat", 0)
        global.Cut1 = ini_read_real("Cutscenes", "Cut1", 0)
        global.Cut2 = ini_read_real("Cutscenes", "Cut2", 0)
        global.Cut3 = ini_read_real("Cutscenes", "Cut3", 0)
        global.Cut4 = ini_read_real("Cutscenes", "Cut4", 0)
        global.Cut5 = ini_read_real("Cutscenes", "Cut5", 0)
ini_close()
}else{
ini_open("FNASSave.r2save")
    ini_write_real("Save", "Night", global.Night)
    ini_write_real("Unlocks", "Night 6", global.N6)
    ini_write_real("Unlocks", "Extras", global.Extras)
    ini_write_real("Stars", "Night 5", global.N5Star)
    ini_write_real("Stars", "Night 6", global.N6Star)
    ini_write_real("Stars", "4/20", global.Four20Star)
    ini_write_real("Stars", "Night 8", global.N8Star)
    ini_write_real("Stars", "Ring's Night", global.RingStar)
    ini_write_real("Survival", "EasyRecord", global.SurvEasy)
    ini_write_real("Survival", "MediumRecord", global.SurvMed)
    ini_write_real("Survival", "HardRecord", global.SurvHard)
    ini_write_real("Plushies", "Golden", global.GoldenPlush)
    ini_write_real("Plushies", "Sonic", global.SonicPlush)
    ini_write_real("Plushies", "Mario", global.MarioPlush)
    ini_write_real("Plushies", "Yoshi", global.YoshiPlush)
    ini_write_real("Plushies", "Tails", global.TailsPlush)
    ini_write_real("Plushies", "Ring", global.RingPlush)
    ini_write_real("Plushies", "Jaxon", global.JaxonPlush)
    ini_write_real("Plushies", "Zerty", global.ZertyPlush)
    ini_write_real("Plushies", "BlueFox", global.BlueFoxPlush)
    ini_write_real("Cutscenes", "Cut1", global.Cut1)
    ini_write_real("Cutscenes", "Cut2", global.Cut2)
    ini_write_real("Cutscenes", "Cut3", global.Cut3)
    ini_write_real("Cutscenes", "Cut4", global.Cut4)
    ini_write_real("Cutscenes", "Cut5", global.Cut5)
ini_close()}

