ini_open("FNASSave.r2save")
    ini_write_real("Save", "Night", global.Night)
    ini_write_real("Unlocks", "Night 6", global.N6)
    ini_write_real("Unlocks", "Extras", global.Extras)ini_write_real("Stars", "Night 5", global.N5Star)
    ini_write_real("Stars", "Night 5", global.N5Star)
    ini_write_real("Stars", "Night 6", global.N6Star)
    ini_write_real("Stars", "5/20", global.Four20Star)
    ini_write_real("Stars", "Night 8", global.N8Star)
    ini_write_real("Stars", "Ring's Night", global.RingStar)
    ini_write_real("Survival", "Record", global.SurvRecord)
    ini_write_real("Survival", "MediumRecord", global.SurvMed)
    ini_write_real("Survival", "HardRecord", global.SurvHard)
    ini_write_real("Plushies", "Golden", global.GoldenPlush)
    ini_write_real("Plushies", "Sonic", global.SonicPlush)
    ini_write_real("Plushies", "Mario", global.MarioPlush)
    ini_write_real("Plushies", "Yoshi", global.YoshiPlush)
    ini_write_real("Plushies", "Tails", global.TailsPlush)
    ini_write_real("Plushies", "Ring", global.RingPlush)
    ini_write_real("Plushies", "Jaxon", global.JaxonPlush)
    ini_write_real("Plushies", "Zerty", global.ZertyPlush)
    ini_write_real("Plushies", "BlueFox", global.BlueFoxPlush)
    ini_write_real("Plushies", "RingHat", global.RingHat)
    ini_write_real("Cutscenes", "Cut1", global.Cut1)
    ini_write_real("Cutscenes", "Cut2", global.Cut2)
    ini_write_real("Cutscenes", "Cut3", global.Cut3)
    ini_write_real("Cutscenes", "Cut4", global.Cut4)
    ini_write_real("Cutscenes", "Cut5", global.Cut5)
ini_close()
